AirFrance.WebUI/Models/ErrorViewModel.cs
namespace AirFrance.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AirFrance.WebUI/Models/PassagerListViewModel.cs
using AirFrance.Model;

namespace AirFrance.WebUI.Models;

public class PassagerListViewModel
{
    public string PageTitle { get; set; }

    public List<Passager> Passagers { get; set; }
}

AirFrance.WebUI/Models/VolListViewModel.cs
using AirFrance.Model;

namespace AirFrance.WebUI.Models;

public class VolListViewModel
{
    public string PageTitle { get; set; }

    public List<Vol> Vols { get; set; }
}

AirFrance.WebUI/Controllers/HomeController.cs
using AirFrance.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AirFrance.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AirFrance.WebUI/Controllers/PassagerController.cs
using AirFrance.DataProvider;
using AirFrance.DataProvider.Interfaces;
using AirFrance.Model;
using AirFrance.Models;
using AirFrance.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Resources;

namespace AirFrance.Controllers
{
    public class PassagerController : Controller
    {
        private readonly ILogger<PassagerController> _logger;
        public IPassagerDataProvider PassagerDataProvider { get; set; }

        public PassagerController(ILogger<PassagerController> logger, IPassagerDataProvider PassagerDataProvider)
        {
            _logger = logger;
            this.PassagerDataProvider = PassagerDataProvider;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var Passagers = PassagerDataProvider.GetMyPassagers().ToList();

            PassagerListViewModel model = new()
            {
                PageTitle = ""
            };

            if (Passagers != null)
            {
                model.Passagers = Passagers;
            }

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AirFrance.WebUI/Controllers/VolController.cs
using AirFrance.DataProvider.Interfaces;
using AirFrance.Model;
using AirFrance.Models;
using AirFrance.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Resources;

namespace AirFrance.Controllers
{
    public class VolController : Controller
    {
        private readonly ILogger<VolController> _logger;
        public IVolDataProvider volDataProvider { get; set; }

        public VolController(ILogger<VolController> logger, IVolDataProvider volDataProvider)
        {
            _logger = logger;
            this.volDataProvider = volDataProvider;
        }

        public IActionResult Index()
        {
            var Vols = volDataProvider.GetMyFlights().ToList();

            VolListViewModel model = new()
            {
                PageTitle = ""
            };

            if (Vols != null)
            {
                model.Vols = Vols;
            }

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AirFrance.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AirFrance.WebUI/Views/Passager/Index.cshtml
@using AirFrance.WebUI.Models
@model PassagerListViewModel

@{
    ViewData["Title"] = Model.PageTitle;
}
@*Affichage via une vue partielle*@
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">FirstName</th>
            <th scope="col">LastName</th>
            <th scope="col">Birthdate</th>
            <th scope="col">IsCheckedId</th>
            <th scope="col">TicketPrice</th>
            <th scope="col">Vol</th>
        </tr>
    </thead>
    @foreach (var passager in Model.Passagers)
    {
        <partial name="Partials/_PassagersList" model="@passager" />
    }
</table>

<a class="btn btn-primary" asp-area="" asp-controller="Passager" asp-action="Add">+ Add</a>

AirFrance.WebUI/Views/Shared/Partials/_PassagersList.cshtml
@using AirFrance.Model
@model Passager

<tr>
    <th scope="row">@Model.Id</th>
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    <td>@Model.Birthdate</td>
    <td>@Model.IsCheckedId</td>
    <td>@Model.TicketPrice</td>
    <td>
        <p>@Model.Vol.Destination</p>
        <p>@Model.Vol.TakeOffDate</p>
    </td>
</tr>

AirFrance.WebUI/Views/Shared/Partials/_VolsList.cshtml
@using AirFrance.Model
@model Vol

<div class="row">
    <div class="col">@Model.Id</div>
    <div class="col">@Model.Destination</div>
    <div class="col">@Model.TakeOffDate</div>
    <div class="col">@Model.IsDelayed</div>
    <div class="col">@Model.OnBoardingMessage</div>
    <div class="col">@Model.Passagers.Count / @Model.SeatCount passagers</div>
    <div class="col">@Model.NetSales</div>
    <div class="col"><a asp-controller="Game" asp-action="AddOrEdit" asp-route-id="@Model.Id">Modifier</a></div>
</div>

AirFrance.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AirFrance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AirFrance.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AirFrance</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vol" asp-action="Index">Vols</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passager" asp-action="Index">Passagers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AirFrance - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AirFrance.WebUI/Views/Vol/Index.cshtml
@using AirFrance.WebUI.Models
@model VolListViewModel

@{
    ViewData["Title"] = Model.PageTitle;
}
@*Affichage via une vue partielle*@
@foreach (var vol in Model.Vols)
{
    <partial name="Partials/_VolsList" model="@vol"/>
}

<a class="btn btn-primary" asp-area="" asp-controller="Vol" asp-action="Add">+ Add</a>